language: cpp
compiler:
    - g++
    - clang++
   
os:
    - linux
    - osx

sudo: yes
install: 
    - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install -y uuid-dev; else echo "For now not support osx!"; fi
    - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install -y python2.7-dev; else echo "For now not support osx!"; fi
    - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF; else echo "For now not support osx!"; fi
    - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list; else echo "For now not support osx!"; fi
    - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get update; else echo "For now not support osx!"; fi
    - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install -y mono-complete; else echo "For now not support osx!"; fi

script:
    # core library about make instructions
    - make core_lib -j4 # make c++ core library
    - make test -j4     # make c++ core library testsuite
    # wrap library about make instructions
    - make cs_wrap -j4  # make csharp wrap library
    - make lu_wrap      # make lua wrap library

notifications:
    email:
        recipients:
            - lailongwei@126.com # Longwei Lai
            - 964855959@qq.com   # Longwei Lai
            - 852917130@qq.com   # Huasheng Liu
        on_success: change
        on_failure: always

