version: 1.0.6.{build}
max_jobs: 8
branches:
    only:
        - master

clone_depth: 50
clone_folder: c:\projects\llbc
install:
    - cmd: >-
        git submodule update --init --recursive
        
        echo vs2013 | call WinPreBuild.bat 0
        
        echo vs2015 | call WinPreBuild.bat 0
image: 
    - Visual Studio 2013
    - Visual Studio 2015

configuration: 
    - release32
    - release64

platform: 
    - x86
    - x64

for:
-
    matrix:
        exclude:
            - configuration: release32
              platform: x64

            - configuration: release64
              platform: x86

build:
    verbosity: normal
    project: build\vs2013\llbc_vs2013.sln
